// ── academy/linux-lessons.ts ───────────────────────────────────────
// Subsección Linux del path Sistemas Operativos.
// 5 lecciones: historia/filosofía → terminal → comandos → archivos → permisos.

import type { Lesson } from '../types';

export const LINUX_LESSONS: Lesson[] = [
  {
    id: 'linux-01',
    pathId: 'os',
    order: 1,
    title: 'Why Linux: history, free software and where it lives',
    titleEs: 'Por qué Linux: historia, software libre y dónde vive',
    readingMinutes: 8,
    steps: [
      {
        type: 'foxy-narrator',
        messages: [
          {
            es: 'Antes de hackear un Linux, vale la pena entender qué es y por qué existe. Esta lección es historia y filosofía — pero sin ella los comandos no tienen sentido.',
            en: "Before hacking a Linux box, it's worth understanding what it is and why it exists. This lesson is history and philosophy — but without it the commands make no sense.",
          },
        ],
      },
      {
        type: 'content',
        title: '1991: a Finnish student and a hobby',
        titleEs: '1991: un estudiante finlandés y un hobby',
        body: 'Linus Torvalds posted on a forum: "I\'m doing a (free) operating system (just a hobby, won\'t be big and professional...)". That hobby became the Linux kernel, the core that today runs most of the internet.',
        bodyEs: 'Linus Torvalds publicó en un foro: "Estoy haciendo un sistema operativo (libre, solo un hobby, no va a ser grande ni profesional...)". Ese hobby se convirtió en el kernel Linux, el núcleo que hoy corre la mayor parte de internet.',
      },
      {
        type: 'video',
        src: '/videos/es/li01-linux-history.mp4',
        srcEn: '/videos/en/li01-linux-history.mp4',
        durationSec: 75,
        caption: 'Born in 1991 as a hobby by Linus Torvalds. Linux is the kernel; GNU provides the programs. The 4 freedoms let you study, modify and share the source code — that is why it is the hacker\'s OS.',
        captionEs: 'Nació en 1991 como hobby de Linus Torvalds. Linux es el kernel; GNU aporta los programas. Las 4 libertades te dejan estudiar, modificar y compartir el código fuente — por eso es el SO del hacker.',
      },
      {
        type: 'content',
        title: 'Where Linux actually runs',
        titleEs: 'Dónde corre Linux realmente',
        body: 'Web servers: 70%+ of the internet. Android: a modified Linux kernel. Cloud: AWS, Google Cloud, Azure mostly run Linux. Even your smart TV, router and car probably have Linux inside. Windows rules the desktop; Linux rules everything else.',
        bodyEs: 'Servidores web: más del 70% de internet. Android: un kernel Linux modificado. Cloud: AWS, Google Cloud, Azure corren casi todo Linux. Incluso tu smart TV, tu router y tu auto probablemente tienen Linux adentro. Windows domina el escritorio; Linux domina todo lo demás.',
      },
      {
        type: 'content',
        title: 'Free software: the 4 freedoms',
        titleEs: 'Software libre: las 4 libertades',
        body: 'Freedom to RUN the program for any purpose. Freedom to STUDY how it works (and read the source code). Freedom to REDISTRIBUTE copies. Freedom to IMPROVE and share your changes. That last one is why Linux got so good: thousands of eyes fixing it.',
        bodyEs: 'Libertad de EJECUTAR el programa para cualquier propósito. Libertad de ESTUDIAR cómo funciona (y leer el código fuente). Libertad de REDISTRIBUIR copias. Libertad de MEJORAR y compartir tus cambios. Esta última es por la que Linux se volvió tan bueno: miles de ojos mejorándolo.',
      },
      {
        type: 'terminal-demo',
        command: 'uname -a',
        output: 'Linux kali 6.5.0-kali3-amd64 #1 SMP Debian 6.5.6-1kali1 (2023-10-09) x86_64 GNU/Linux',
        explanation: 'Every Linux shows its kernel version with uname. Ubuntu uses one branch, Kali another, but underneath it\'s all Linux. Same commands, same files, same concepts.',
        explanationEs: 'Todo Linux muestra su kernel con uname. Ubuntu usa una rama, Kali otra, pero debajo es todo Linux. Mismos comandos, mismos archivos, mismos conceptos.',
      },
      {
        type: 'content',
        title: 'Linux vs proprietary Windows',
        titleEs: 'Linux vs Windows privativo',
        body: 'Windows: closed source, you pay for the license, you can\'t read the code, you can\'t share it modified. Linux: open source, free of cost, you can read every line, you can copy it, modify it, sell it. Why this matters for hacking: with Linux you can see EXACTLY what the OS does. No secrets.',
        bodyEs: 'Windows: código cerrado, pagás la licencia, no podés leer el código, no podés compartirlo modificado. Linux: código abierto, sin costo, podés leer cada línea, copiarlo, modificarlo, venderlo. Por qué importa para hacking: con Linux podés ver EXACTAMENTE lo que hace el SO. Sin secretos.',
      },
      {
        type: 'quiz',
        question: 'Which of these is NOT one of the 4 freedoms of free software?',
        questionEs: '¿Cuál de estas NO es una de las 4 libertades del software libre?',
        options: [
          { es: 'Ejecutar el programa para cualquier propósito', en: 'Run the program for any purpose' },
          { es: 'Estudiar cómo funciona', en: 'Study how it works' },
          { es: 'Que sea siempre gratis (sin costo)', en: 'That it must always be free of charge' },
          { es: 'Mejorar y compartir tus cambios', en: 'Improve and share your changes' },
        ],
        correctIndex: 2,
      },
    ],
  },
  {
    id: 'linux-02',
    pathId: 'os',
    order: 2,
    title: 'The terminal: shells, PATH, prompt and flags',
    titleEs: 'La terminal: shells, PATH, prompt y flags',
    readingMinutes: 9,
    steps: [
      {
        type: 'foxy-narrator',
        messages: [
          {
            es: 'La terminal es tu interfaz con el sistema. No hagas click: escribe comandos. Este paso te muestra qué estás viendo cuando abrís una.',
            en: "The terminal is your interface with the system. Don't click: type commands. This step shows you what you're looking at when you open one.",
          },
        ],
      },
      {
        type: 'content',
        title: 'What is a shell?',
        titleEs: '¿Qué es una shell?',
        body: 'The shell is the program that reads your commands and runs them. Most common: `bash` (Bourne Again Shell, the default in almost every Linux), `zsh` (more colorful, default on macOS), `sh` (minimal, everywhere). They all run the same basic commands.',
        bodyEs: 'La shell es el programa que lee tus comandos y los ejecuta. Las más comunes: `bash` (Bourne Again Shell, default en casi todo Linux), `zsh` (más colorida, default en macOS), `sh` (mínima, en todas partes). Todas corren los mismos comandos base.',
      },
      {
        type: 'video',
        src: '/videos/es/li02-shell.mp4',
        srcEn: '/videos/en/li02-shell.mp4',
        durationSec: 111,
        caption: 'The prompt: kali@attacker-01:~$ reads user, machine, directory and permissions. Anatomy of a command: program + flags + argument. $ vs # (root).',
        captionEs: 'El prompt: kali@attacker-01:~$ se lee usuario, máquina, directorio y permisos. Anatomía de un comando: programa + flags + argumento. $ vs # (root).',
      },
      {
        type: 'content',
        title: 'Windows equivalents: CMD, PowerShell, WSL',
        titleEs: 'Equivalentes en Windows: CMD, PowerShell, WSL',
        body: '`cmd.exe` is the classic Windows terminal (DOS-era). `powershell.exe` is much more powerful: objects instead of text. `WSL` (Windows Subsystem for Linux) runs a real Linux inside Windows. For pentest practice you want a Linux shell — but knowing PowerShell helps in Windows targets.',
        bodyEs: '`cmd.exe` es la terminal clásica de Windows (era DOS). `powershell.exe` es mucho más poderosa: objetos en vez de texto. `WSL` (Windows Subsystem for Linux) corre un Linux real dentro de Windows. Para practicar pentest querés una shell de Linux — pero conocer PowerShell ayuda en targets Windows.',
      },
      {
        type: 'terminal-demo',
        command: 'echo $PATH',
        output: '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin',
        explanation: 'When you type `nmap`, the shell searches those directories in order for a binary named nmap. If it\'s not there: "command not found". You can add your own dirs with export.',
        explanationEs: 'Cuando escribís `nmap`, la shell busca en esos directorios en orden un binario llamado nmap. Si no está ahí: "command not found". Podés agregar tus propios directorios con export.',
      },
      {
        type: 'terminal-demo',
        command: '',
        output: 'kali@attacker-01:~$ nmap -sV -p- 192.168.1.11',
        explanation: 'Anatomy of a command: `nmap` is the program, `-sV` and `-p-` are flags (options). Flags modify behavior. `--help` or `man nmap` tells you all of them.',
        explanationEs: 'Anatomía de un comando: `nmap` es el programa, `-sV` y `-p-` son flags (opciones). Los flags modifican el comportamiento. `--help` o `man nmap` te lista todos.',
      },
      {
        type: 'content',
        title: 'Reading the prompt',
        titleEs: 'Leyendo el prompt',
        body: '`kali@attacker-01:~$` reads: user kali ON machine attacker-01 IN directory ~ (the user\'s home). `$` = normal user. `#` = root. When you see `#`, you have full control.',
        bodyEs: '`kali@attacker-01:~$` se lee: usuario kali EN la máquina attacker-01 EN el directorio ~ (el home del usuario). `$` = usuario normal. `#` = root. Cuando ves `#`, tenés control total.',
      },
      {
        type: 'practical-exercise',
        task: 'Open the terminal and explore your environment: try `pwd`, `whoami`, `echo $PATH`. What do you see? Try `echo $SHELL` to see which shell you\'re using.',
        taskEs: 'Abrí la terminal y explorá tu entorno: probá `pwd`, `whoami`, `echo $PATH`. ¿Qué ves? Probá `echo $SHELL` para ver qué shell estás usando.',
        hint: 'Start with: pwd (where am I) and whoami (who am I). Then try echo $PATH to see the program search dirs.',
        hintEs: 'Empezá con: pwd (dónde estoy) y whoami (quién soy). Después echo $PATH para ver los directorios donde se buscan programas.',
        labId: 'scenario-01',
      },
      {
        type: 'quiz',
        question: 'In the prompt `root@server:/etc#`, what does the `#` symbol indicate?',
        questionEs: 'En el prompt `root@server:/etc#`, ¿qué indica el símbolo `#`?',
        options: [
          { es: 'Estás en el directorio /etc', en: 'You are in /etc directory' },
          { es: 'Sos el usuario root (control total)', en: 'You are the root user (full control)' },
          { es: 'El servidor está identificado', en: 'The server is identified' },
          { es: 'Hay un comando corriendo', en: 'A command is running' },
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'linux-03',
    pathId: 'os',
    order: 3,
    title: 'Core commands: pwd, echo, id, ls',
    titleEs: 'Comandos base: pwd, echo, id, ls',
    readingMinutes: 8,
    steps: [
      {
        type: 'foxy-narrator',
        messages: [
          {
            es: 'Hay 4 comandos que vas a usar mil veces: `pwd` (dónde estoy), `echo` (imprimir), `id` (quién soy), `ls` (qué hay aquí). Son tu GPS en cualquier Linux.',
            en: "There are 4 commands you'll use a thousand times: `pwd` (where am I), `echo` (print), `id` (who am I), `ls` (what's here). They're your GPS in any Linux.",
          },
        ],
      },
      {
        type: 'video',
        src: '/videos/es/li03-commands.mp4',
        srcEn: '/videos/en/li03-commands.mp4',
        durationSec: 65,
        caption: 'pwd (where am I), id (who am I), ls -la (what is here), echo + redir (write/read files). The 4 you will use daily.',
        captionEs: 'pwd (dónde estoy), id (quién soy), ls -la (qué hay), echo + redir (escribir/leer). Los 4 que usarás a diario.',
      },
      {
        type: 'terminal-demo',
        command: 'pwd',
        output: '/home/kali',
        explanation: 'Print Working Directory: shows your absolute path. You always know where you are in the tree.',
        explanationEs: 'Print Working Directory: muestra tu ruta absoluta. Siempre sabes dónde estás en el árbol.',
      },
      {
        type: 'terminal-demo',
        command: 'id',
        output: 'uid=1000(kali) gid=1000(kali) groups=1000(kali),4(adm),27(sudo),142(kaboxer)',
        explanation: 'Shows your user ID, group ID, and all groups you belong to. If you see `sudo` in groups: you can become root with sudo. If not: harder.',
        explanationEs: 'Muestra tu ID de usuario, ID de grupo, y todos los grupos a los que perteneces. Si ves `sudo` en grupos: podés volverte root con sudo. Si no: es más difícil.',
      },
      {
        type: 'terminal-demo',
        command: 'ls -la',
        output: 'drwxr-xr-x  5 kali kali 4096 Mar 19 10:00 .\ndrwxr-xr-x  3 root root 4096 Mar 19 09:00 ..\n-rw-------  1 kali kali  220 Mar 19 10:00 .bash_history\n-rw-r--r--  1 kali kali 3523 Mar 19 09:00 .bashrc\ndrwx------  2 kali kali 4096 Mar 19 10:00 .ssh',
        explanation: '`-l` shows long format (permissions, owner, size, date), `-a` shows hidden files (those starting with dot). `.bash_history` is gold for looting: it shows everything the user typed.',
        explanationEs: '`-l` muestra formato largo (permisos, dueño, tamaño, fecha), `-a` muestra archivos ocultos (los que empiezan con punto). `.bash_history` es oro para looteo: muestra todo lo que tipeó el usuario.',
      },
      {
        type: 'terminal-demo',
        command: 'echo "texto" > /tmp/nota.txt && cat /tmp/nota.txt',
        output: 'texto',
        explanation: '`echo` prints. `>` redirects output to a file (creates or overwrites). `>>` appends. This is how you drop payloads and notes on a target.',
        explanationEs: '`echo` imprime. `>` redirige la salida a un archivo (crea o sobreescribe). `>>` agrega. Así es como dejás payloads y notas en un objetivo.',
      },
      {
        type: 'practical-exercise',
        task: 'In the terminal below, run each command and observe the output: pwd, id, ls -la. Then create a file with echo: `echo "hola" > /tmp/test.txt` and read it with cat.',
        taskEs: 'En la terminal de abajo, ejecutá cada comando y observá la salida: pwd, id, ls -la. Después creá un archivo con echo: `echo "hola" > /tmp/test.txt` y leélo con cat.',
        hint: 'All four commands accept no arguments (just run them as-is). The only one that cares is `ls -la` for the long format.',
        hintEs: 'Los cuatro comandos funcionan sin argumentos (tal cual). El único que usa flag es `ls -la` para formato largo.',
        labId: 'scenario-01',
      },
      {
        type: 'quiz',
        question: 'If `id` shows your groups include `sudo`, what can you do?',
        questionEs: 'Si `id` muestra que tus grupos incluyen `sudo`, ¿qué podés hacer?',
        options: [
          { es: 'Leer archivos ocultos', en: 'Read hidden files' },
          { es: 'Ejecutar comandos como root con sudo', en: 'Run commands as root with sudo' },
          { es: 'Cambiar de directorio a /etc', en: 'Change directory to /etc' },
          { es: 'Ver la contraseña de otros usuarios', en: "See other users' passwords" },
        ],
        correctIndex: 1,
      },
    ],
  },
  {
    id: 'linux-04',
    pathId: 'os',
    order: 4,
    title: 'Creating and editing: touch, mkdir, nano',
    titleEs: 'Crear y editar: touch, mkdir, nano',
    readingMinutes: 8,
    steps: [
      {
        type: 'foxy-narrator',
        messages: [
          {
            es: 'En un objetivo vas a crear carpetas para tus herramientas, archivos para tus notas, y editar configs. Estos 3 comandos son tu caja de herramientas para "construir" en el sistema.',
            en: "On a target you'll create folders for your tools, files for your notes, and edit configs. These 3 commands are your toolbox for 'building' on the system.",
          },
        ],
      },
      {
        type: 'video',
        src: '/videos/es/li04-create-edit.mp4',
        srcEn: '/videos/en/li04-create-edit.mp4',
        durationSec: 71,
        caption: 'mkdir creates a folder, touch a file, nano opens the editor. Work from /tmp — always world-writable.',
        captionEs: 'mkdir crea carpeta, touch un archivo, nano abre el editor. Trabaja desde /tmp — escribible por todos.',
      },
      {
        type: 'terminal-demo',
        command: 'mkdir herramientas && touch herramientas/wordlist.txt && ls herramientas/',
        output: 'wordlist.txt',
        explanation: 'mkdir creates a directory. touch creates an empty file (or updates the timestamp if it exists). Combine them to organize your workspace.',
        explanationEs: 'mkdir crea un directorio. touch crea un archivo vacío (o actualiza la fecha si ya existe). Combinándolos organizás tu espacio de trabajo.',
      },
      {
        type: 'terminal-demo',
        command: 'rmdir directorio_vacio',
        output: '(no output — success)',
        explanation: 'rmdir deletes EMPTY directories. If it has files inside: "Directory not empty". Use `rm -r` to force delete with contents (dangerous).',
        explanationEs: 'rmdir borra directorios VACÍOS. Si tiene archivos adentro: "Directory not empty". Usá `rm -r` para forzar el borrado con contenido (peligroso).',
      },
      {
        type: 'terminal-demo',
        command: 'nano nota.txt',
        output: '[GNU nano — editor opens fullscreen]\n^G Get Help  ^O Write Out  ^X Exit',
        explanation: 'nano is the simplest editor. Ctrl+O saves (Write Out), Ctrl+X exits. Perfect for quick edits on a target when you don\'t have a graphical editor.',
        explanationEs: 'nano es el editor más simple. Ctrl+O guarda (Write Out), Ctrl+X sale. Perfecto para ediciones rápidas en un objetivo cuando no tenés editor gráfico.',
      },
      {
        type: 'content',
        title: 'Permissions apply when creating',
        titleEs: 'Los permisos aplican al crear',
        body: 'You can only `touch` / `mkdir` in directories where you have WRITE permission. `/tmp` works (world-writable). `/etc` fails for normal users (root only). This is why attackers work from /tmp or /dev/shm.',
        bodyEs: 'Solo podés `touch` / `mkdir` en directorios donde tenés permiso de ESCRITURA. `/tmp` funciona (escritura global). `/etc` falla para usuarios normales (solo root). Por eso los atacantes trabajan desde /tmp o /dev/shm.',
      },
      {
        type: 'practical-exercise',
        task: 'Create your workspace in /tmp: `mkdir /tmp/trabajo`, then a note file `touch /tmp/trabajo/notas.txt`. Edit it with `nano /tmp/trabajo/notas.txt`, write something, save with Ctrl+O and exit with Ctrl+X.',
        taskEs: 'Creá tu espacio de trabajo en /tmp: `mkdir /tmp/trabajo`, después un archivo de notas `touch /tmp/trabajo/notas.txt`. Editálo con `nano /tmp/trabajo/notas.txt`, escribí algo, guardá con Ctrl+O y salí con Ctrl+X.',
        hint: 'Steps in order: 1) mkdir /tmp/trabajo  2) touch /tmp/trabajo/notas.txt  3) nano opens the editor. Inside: type something, Ctrl+O to save, Enter to confirm, Ctrl+X to exit.',
        hintEs: 'Pasos en orden: 1) mkdir /tmp/trabajo  2) touch /tmp/trabajo/notas.txt  3) nano abre el editor. Adentro: escribí algo, Ctrl+O para guardar, Enter para confirmar, Ctrl+X para salir.',
        labId: 'scenario-01',
      },
      {
        type: 'quiz',
        question: 'Which command allows you to edit a text file inside the terminal?',
        questionEs: '¿Qué comando te permite editar un archivo de texto dentro de la terminal?',
        options: [
          { es: 'touch', en: 'touch' },
          { es: 'mkdir', en: 'mkdir' },
          { es: 'nano', en: 'nano' },
          { es: 'rmdir', en: 'rmdir' },
        ],
        correctIndex: 2,
      },
    ],
  },
  {
    id: 'linux-05',
    pathId: 'os',
    order: 5,
    title: 'Permissions: rwx, octal, owner/group/others and special bits',
    titleEs: 'Permisos: rwx, octal, dueño/grupo/otros y bits especiales',
    readingMinutes: 10,
    steps: [
      {
        type: 'foxy-narrator',
        messages: [
          {
            es: 'Esta es LA lección clave para la escalada de privilegios. Entender permisos = entender por qué a veces ganas acceso total con un solo comando mal configurado.',
            en: 'This is THE key lesson for privilege escalation. Understanding permissions = understanding why sometimes you get full access with a single misconfigured command.',
          },
        ],
      },
      {
        type: 'video',
        src: '/videos/es/li05-permissions.mp4',
        srcEn: '/videos/en/li05-permissions.mp4',
        durationSec: 110,
        caption: 'rwx = read/write/execute. 644 = owner edits, others read. SUID (s) = run as the owner — root. The key to privesc.',
        captionEs: 'rwx = leer/escribir/ejecutar. 644 = dueño edita, otros leen. SUID (s) = correr como el dueño — root. La llave de la escalada.',
      },
      {
        type: 'terminal-demo',
        command: 'ls -la /usr/bin/su',
        output: '-rwsr-xr-x 1 root root 67816 Mar 19 10:00 /usr/bin/su',
        explanation: 'Break down `-rwsr-xr-x`: `-` file type. `rws` — owner root has read+write+execute+SUID (s instead of x). `r-x` — group root: read+execute. `r-x` — others: read+execute.',
        explanationEs: 'Descomponemos `-rwsr-xr-x`: `-` tipo archivo. `rws` — el dueño root tiene lectura+escritura+ejecución+SUID (s en vez de x). `r-x` — grupo root: leer+ejecutar. `r-x` — otros: leer+ejecutar.',
      },
      {
        type: 'content',
        title: 'The 3 levels: owner / group / others',
        titleEs: 'Los 3 niveles: dueño / grupo / otros',
        body: 'Every file has an owner (a user), a group, and "others". Permissions are checked in order: are you the owner? apply owner perms. Are you in the group? apply group perms. Else: others perms. Root bypasses everything.',
        bodyEs: 'Cada archivo tiene un dueño (un usuario), un grupo, y "otros". Los permisos se chequean en orden: ¿sos el dueño? aplican permisos de dueño. ¿estás en el grupo? aplican permisos de grupo. Si no: permisos de otros. Root ignora todo.',
      },
      {
        type: 'content',
        title: 'Octal: 644, 755, 4755',
        titleEs: 'Octal: 644, 755, 4755',
        body: 'Each permission triplet is a number: r=4, w=2, x=1. Sum them: rw- = 6, r-x = 5, rwx = 7. So 644 = rw- r-- r-- (owner can edit, others can only read). 755 = rwx r-x r-x (executable by all). A leading 4 = SUID, 2 = SGID, 1 = sticky bit.',
        bodyEs: 'Cada triplete de permisos es un número: r=4, w=2, x=1. Los sumás: rw- = 6, r-x = 5, rwx = 7. Entonces 644 = rw- r-- r-- (el dueño edita, otros solo leen). 755 = rwx r-x r-x (ejecutable por todos). Un 4 al inicio = SUID, 2 = SGID, 1 = sticky bit.',
      },
      {
        type: 'terminal-demo',
        command: 'find / -perm -4000 -type f 2>/dev/null',
        output: '/usr/bin/su\n/usr/bin/sudo\n/usr/bin/passwd\n/usr/bin/find\n/usr/bin/vim',
        explanation: 'This is how attackers find SUID binaries: files that run as their owner (usually root) no matter who calls them. If vim is SUID root, you can open /etc/shadow as root inside vim.',
        explanationEs: 'Así encuentran los atacantes los binarios SUID: archivos que corren como su dueño (generalmente root) sin importar quién los llame. Si vim es SUID root, podés abrir /etc/shadow como root desde vim.',
      },
      {
        type: 'content',
        title: 'Sticky bit on /tmp',
        titleEs: 'Sticky bit en /tmp',
        body: '/tmp is world-writable (anyone can create files) BUT has the sticky bit: only the file owner can delete their files. That\'s why you can drop a payload in /tmp and another user can\'t delete it. Shown as `t` in the last position: `drwxrwxrwt`.',
        bodyEs: '/tmp es escribible por todos (cualquiera puede crear archivos) PERO tiene el sticky bit: solo el dueño del archivo puede borrarlo. Por eso podés dejar un payload en /tmp y otro usuario no lo puede borrar. Se muestra como `t` en la última posición: `drwxrwxrwt`.',
      },
      {
        type: 'practical-exercise',
        task: 'Explore permissions in the terminal: run `ls -la /etc/passwd /etc/shadow /tmp` and read each line. Then find SUID binaries with `find / -perm -4000 -type f 2>/dev/null`. What would it mean if vim appears in the list?',
        taskEs: 'Explorá permisos en la terminal: corré `ls -la /etc/passwd /etc/shadow /tmp` y leé cada línea. Después buscá binarios SUID con `find / -perm -4000 -type f 2>/dev/null`. ¿Qué significa que vim aparezca en la lista?',
        hint: '-4000 means "any file with the SUID bit set". 2>/dev/null hides permission errors. If vim is SUID, you can open protected files as root.',
        hintEs: '-4000 significa "cualquier archivo con el bit SUID activado". 2>/dev/null oculta los errores de permiso. Si vim es SUID, podés abrir archivos protegidos como root.',
        labId: 'scenario-06',
      },
      {
        type: 'quiz',
        question: 'You find a binary with permissions `-rwsr-xr-x root root`. What happens when you run it as a normal user?',
        questionEs: 'Encontrás un binario con permisos `-rwsr-xr-x root root`. ¿Qué pasa cuando lo ejecutás como usuario normal?',
        options: [
          { es: 'Corre con tus permisos normales', en: 'It runs with your normal permissions' },
          { es: 'Corre COMO ROOT (SUID)', en: 'It runs AS ROOT (SUID)' },
          { es: 'Fallará por falta de permisos', en: 'It will fail due to missing permissions' },
          { es: 'Te pregunta la contraseña de root', en: 'It asks for the root password' },
        ],
        correctIndex: 1,
      },
    ],
  },
];
