// ── commands/help/whatis.ts ───────────────────────────────────────
// One-liners por comando para `whatis` y `apropos` (Tier 1).

export const WHATIS: Record<string, string> = {
  alias: 'define or display aliases',
  apropos: 'search the manual page names and descriptions',
  'apt': 'package manager (update/install/remove/list)',
  'arp-scan': 'discover active hosts on the network',
  cat: 'concatenate and display files',
  cd: 'change the working directory',
  chgrp: 'change group ownership',
  chmod: 'change file permissions',
  chown: 'change file owner',
  clear: 'clear the terminal screen',
  column: 'align output into a table',
  cp: 'copy files and directories',
  crontab: 'manage scheduled tasks',
  curl: 'transfer data from URLs',
  cut: 'remove sections from lines',
  date: 'show the current (virtual) time',
  df: 'report filesystem disk space usage',
  diff: 'compare files line by line',
  dirname: 'strip the last component from a path',
  dig: 'DNS lookup utility',
  dpkg: 'Debian package tool',
  du: 'estimate file space usage',
  echo: 'display text or write to file',
  end: 'exit the lab',
  env: 'show environment variables',
  exit: 'close the session',
  export: 'set an environment variable',
  file: 'determine file type',
  find: 'search for files',
  ftp: 'file transfer client',
  gobuster: 'enumerate web directories',
  grep: 'filter input by pattern',
  groups: 'show group memberships',
  hashcat: 'password hash cracker (simulated)',
  head: 'show the first lines',
  help: 'show available commands',
  history: 'show command history',
  arch: 'print machine architecture',
  free: 'display amount of free and used memory',
  hostname: 'show or set the host name',
  hostnamectl: 'show host name and related information',
  htop: 'interactive process viewer',
  hydra: 'online password brute forcer (simulated)',
  id: 'display user identity',
  ifconfig: 'network interface configuration',
  ip: 'show and manipulate network interfaces',
  iptables: 'manage firewall rules',
  journalctl: 'query the system journal',
  kill: 'terminate processes',
  last: 'show listing of last logged in users',
  less: 'show file contents (pager)',
  lsb_release: 'show distribution information',
  lscpu: 'display CPU information',
  ln: 'create links between files',
  ls: 'list directory contents',
  man: 'display manual pages',
  md5sum: 'compute MD5 checksum',
  mkdir: 'create directories',
  more: 'show file contents (pager)',
  mount: 'show and manage filesystem mounts',
  msfconsole: 'start the Metasploit Framework (simulated)',
  mv: 'move and rename files',
  nano: 'simple text editor',
  nc: 'netcat network utility',
  netdiscover: 'network host discovery',
  netstat: 'network statistics',
  nmap: 'scan ports and services (simulated)',
  nslookup: 'query DNS servers',
  ping: 'test network connectivity',
  ps: 'show process status',
  pwd: 'print the working directory',
  python: 'run Python scripts (simulated)',
  python3: 'run Python scripts (simulated)',
  awk: 'pattern scanning with fields',
  base64: 'base64 encode/decode',
  basename: 'strip directory and suffix from a path',
  nl: 'number lines of files',
  realpath: 'print the resolved path',
  rev: 'reverse characters of each line',
  rm: 'remove files and directories',
  rmdir: 'remove empty directories',
  scp: 'secure file copy',
  sha256sum: 'compute SHA-256 checksum',
  sed: 'stream editor',
  service: 'control system services (SysV)',
  sleep: 'wait and advance virtual time',
  sort: 'sort lines of text',
  ss: 'socket statistics',
  ssh: 'connect via SSH (simulated)',
  stat: 'display file status',
  strings: 'print printable sequences',
  su: 'switch user',
  sudo: 'execute a command as root',
  systemctl: 'control system services',
  tac: 'concatenate files in reverse',
  tail: 'show the last lines',
  tcpdump: 'capture network traffic',
  tee: 'copy stdin to files and stdout',
  top: 'real-time process viewer',
  touch: 'create empty files',
  tr: 'translate, squeeze or delete characters',
  traceroute: 'trace the route to a host',
  type: 'describe how a name is interpreted',
  ufw: 'uncomplicated firewall',
  umask: 'set the file creation mask',
  umount: 'unmount a filesystem',
  unalias: 'remove aliases',
  uname: 'print system information',
  uniq: 'remove adjacent duplicate lines',
  vi: 'file editor (simulated)',
  vim: 'file editor (simulated)',
  w: 'show who is logged in',
  unset: 'remove an environment variable',
  uptime: 'show how long the system has been running',
  wc: 'count lines, words and bytes',
  wget: 'download files from the web',
  whatis: 'display one-line manual descriptions',
  which: 'locate a command',
  whoami: 'print the current user',
  whois: 'query domain ownership',
  xrdp: 'open a Remote Desktop (RDP) session (simulated)',
};
